service: <<COURSE_CODE>>-<<YOUR_NUMBER>>-bedrock-function-sls
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  iam:
    role:
      managedPolicies:
        - "arn:aws:iam::aws:policy/AmazonBedrockFullAccess"

functions:
  invokeBedrockRuntime:
    handler: app.handler
    timeout: 900
    memorySize: 128
    url:
      invokeMode: RESPONSE_STREAM
